### ISSUE TITLE
Missing References?

### ISSUE THREAD

**Issue by skram** [JoakimCarlsson/EscapeFromTarkov-Cheat#1]
Thanks for this, very educational. Im digging around seeing how things work but Im unable to get a full build going. It seems there's several references that are missing. Wondering how do I go about installing them? More specifically

> Comfort
> Comfort.Unity
> UnityEngine.CoreModule
> UnityEngine.IMGUIModule
> UnityEngine.UI

I did install the Unity Add-on to Visual Studio in which took care of some warnings/errors.

**Comment by JoakimCarlsson** [comment]
They're are located in the escape from tarkov managed folderSent from my Huawei phone-------- Original message --------From: skram <notifications@github.com>Date: Fri, 6 Mar 2020, 20:01To: JoakimCarlsson/EscapeFromTarkov-Cheat <EscapeFromTarkov-Cheat@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [JoakimCarlsson/EscapeFromTarkov-Cheat] Missing References? (#1)Thanks for this, very educational. Im digging around seeing how things work but Im unable to get a full build going. It seems there's several references that are missing. Wondering how do I go about installing them? More specifically

Comfort
Comfort.Unity
UnityEngine.CoreModule
UnityEngine.IMGUIModule
UnityEngine.UI

I did install the Unity Add-on to Visual Studio in which took care of some warnings/errors.

**Comment by skram** [comment]
I just came back to respond reply to my initial comment that I figured that aspect out. Now it just seems im left with the error(s) for EFT, LootItem, LootableContainer, Player, Skeleton, and ExfiltrationPoint . Appreciate the help! I think this last set of errors will allow me to build it. Im searching around but do not see any of these related references anywhere.

**Comment by JoakimCarlsson** [comment]
Those are located in the assembly.dll I don't know the whole name of it as I'm on my phone now.Sent from my Huawei phone-------- Original message --------From: skram <notifications@github.com>Date: Fri, 6 Mar 2020, 20:28To: JoakimCarlsson/EscapeFromTarkov-Cheat <EscapeFromTarkov-Cheat@noreply.github.com>Cc: Joakim Carlsson <joakimcarlsson1994@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [JoakimCarlsson/EscapeFromTarkov-Cheat] Missing References? (#1)I just came back to respond reply to my initial comment that I figured that aspect out. Now it just seems im left with the error(s) for EFT, LootItem, LootableContainer, Player, Skeleton, and ExfiltrationPoint . Appreciate the help! I think this last set of errors will allow me to build it. Im searching around but do not see any of these related references anywhere.

**Comment by skram** [comment]
Thanks! Figured it out, I had the wrong Assembly-CSharp reference selected. Im now able to build and get the EscapeFromTarkovCheat.dll , BUT not sure what to do with it from here? . Another thing, is this detectable as of right now?

**Comment by JoakimCarlsson** [comment]
You would need a mono injector. Or a way too load it from the managed
folder. It's not undetected without a proper bypass.

**Comment by skram** [comment]
Thanks for such useful information. Do you have a Discord or something I can reach you on? Would like to take conversations offline. Much appreciated.

**Comment by JoakimCarlsson** [comment]
I'm on my phone right now, but if you send your nick I'll add you as soon
as possible.

**Comment by skram** [comment]
is it ok if I send it to you via the email that's associated with your github?
