### ISSUE TITLE
In Game Null Reference Exception

### ISSUE THREAD

**Issue by Ferrarie** [JoakimCarlsson/EscapeFromTarkov-Cheat#3]
Here is my hack process:

        public void InsertCode()
        {
            string filePath = @"Somewhere\EscapeFromTarkovCheat.dll";

            if (File.Exists(filePath))
            {
                Assembly SampleAssembly = Assembly.LoadFrom(filePath);
                Type type = SampleAssembly.GetType("EscapeFromTarkovCheat.Loader");
                MethodInfo methodInfo = type.GetMethod("Load");
                try
                {
                    object obj2 = methodInfo.Invoke(methodInfo.ReturnType, BindingFlags.Static | BindingFlags.InvokeMethod | BindingFlags.Public, null, null, null);
                }
                catch (Exception e)
                {
                    Debug.LogWarning(e);
                }

            }
        }

After successfully insert those codes in DLL, I can see The GUI menu in Game.   Those codes called moment is `UnityEngine.Cursor.SetCursor`(`Texture2D` texture, `Vector2 `hotspot, `CursorMode `cursorMode)

When enable `Draw Players` and `Draw Loot Items` the game Console will start to log a lot of  Null Reference Exception.

**Comment by skram** [comment]
Whats your process on injecting? New to this trying to figure that out.

**Comment by JoakimCarlsson** [comment]
Are you trying too Iterate over objects while you are not ingame, do you still get null references if you are in game?

**Comment by Ferrarie** [comment]
The console Log that the exception comes from PlayerESP.DrawPlayerESP(). 
I think is `_camera == null`. I will check 
this later.

**Comment by Ferrarie** [comment]
> What's your process of injecting? New to this trying to figure that out.

Sorry, the process is quite a bit difficult I am unable to explain that.

**Comment by JoakimCarlsson** [comment]
Instead of using _camers you can Use Camera.main but it takes more time to
execute.

Camera.main returns the first camera that's is called  "MainCamera" so it
will be slower if there are additional cameras. Even though there is none a
direct reference too the camera will be faster.


May I ask you how you load your dll?

**Comment by Ferrarie** [comment]
1. Maybe I should Find all cameras with `Debug.Log` to see them Tags or a better way to ensure the code can lock-on the correct camera.

2. I edit the "Managed\UnityEngine.CoreModule.dll" file because it has no digitally signed.



Function locate in UnityEngine(namespace).Cursor(class).SetCursor(function).
The function insert result :

    public static void SetCursor(Texture2D texture, Vector2 hotspot, CursorMode cursorMode)
    {
        //____________the insert code⬇
        string filePath = @"Somewhere\EscapeFromTarkovCheat.dll";
        if (File.Exists(filePath))
        {
            Assembly SampleAssembly = Assembly.LoadFrom(filePath);
            Type type = SampleAssembly.GetType("EscapeFromTarkovCheat.Loader");
            MethodInfo methodInfo = type.GetMethod("Load");
            try
            {
                object obj2 = methodInfo.Invoke(methodInfo.ReturnType, BindingFlags.Static | BindingFlags.InvokeMethod | BindingFlags.Public, null, null, null);
            }
            catch (Exception e)
            {
                Debug.LogWarning(e);
            }
        }
        //__________the insert code⬆

        Cursor.SetCursor_Injected(texture, ref hotspot, cursorMode);
    }

**Comment by JoakimCarlsson** [comment]
Dosen't BE do integrity checks? So you have too restore your assembly once the cheat assembly loaded?

**Comment by Ferrarie** [comment]
I edit the` Battlestate Games Launcher` too. Make the launcher doesn't check the file consistency. 😝

**Comment by JoakimCarlsson** [comment]
Is there a way I can contact you regarding this. I would like too follow up on this if you don't mind?

**Comment by Ferrarie** [comment]
just use the `de4dot.exe` to de-obfuscate, than reading and understand the Launcher framework.

**Comment by Ferrarie** [comment]
Only on email or wechat

**Comment by JoakimCarlsson** [comment]
I do have WeChat.

**Comment by Ferrarie** [comment]
`SoKingwah`

 my wechatID
