### ISSUE TITLE
Hey Whats up man! any chance you would be interested in helping me get your tarkov cheat up and running with an injector?

### ISSUE THREAD

**Issue by SlootyBlonde** [JoakimCarlsson/EscapeFromTarkov-Cheat#4]

**Comment by JoakimCarlsson** [comment]
I can probably give you a few pointers.
Do you have discord?

**Comment by SlootyBlonde** [comment]
yeah my discord is Slooty Blonde#9214

**Comment by SlootyBlonde** [comment]
sometimes people have trouble adding me for some reason not sure why but if u cant just send me your DC info and i can add you

**Comment by JoakimCarlsson** [comment]
Did not seem too work. Add me JCarlsson#1337

**Comment by SlootyBlonde** [comment]
ok i added you thank you!
